### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by gunnx** [comment]
+1

**Comment by tassilogroeper** [comment]
+1
Still waiting for this one to get merged!

**Comment by psyrendust** [comment]
I'll jump on this today.

**Comment by axten** [comment]
please merge and release it

**Comment by psyrendust** [comment]
Resolved in #7 and published to NPM as [v0.2.9](https://github.com/psyrendust/grunt-svg-css/releases/tag/v0.2.9)

**Pull request closed without merging**
